void Plotefficiency(){
 //------------Root Style----------------------------------------
        gROOT->ForceStyle(); 
        gStyle->SetStatW(0.20);
        gStyle->SetStatH(0.17);
       // gStyle->SetStatFontSize(1.0);
        gStyle->SetOptTitle(1);
        gStyle->SetFuncWidth(3.0);
        gStyle->SetTitleOffset(1.5,"XY");
        gStyle->SetTitleOffset(1.0,"Z");
        gStyle->SetTitleSize(0.07,"A");
       // gStyle->SetTitleFont(62,"A");
	gStyle->SetTitleSize(.05,"X");gStyle->SetTitleSize(.05,"YZ");
	gStyle->SetLabelSize(.04,"X");gStyle->SetLabelSize(.04,"Y");
	gStyle->SetLabelSize(.04,"Z");
	gStyle->SetHistLineWidth(2);
	gStyle->SetOptFit(1);
        //gStyle->SetOptFit(0111);
        gStyle->SetOptStat(0);
   
//----Global variables------------------------        
        
TFile* Limacc2d = TFile::Open("./EfficiencyMap_2D_Dplus5TeV_c_wLimAcc.root");
TFile* Limacc1d = TFile::Open("./EfficiencyMap_1D_Dplus5TeV_c_wLimAcc.root");
//TFile* Genacc1d = TFile::Open("./Acceptance/EfficiencyMap_1D_Dplus5TeV_c_Plot.root");
//fileSEoffline->ls();
TCanvas *canvas = new TCanvas("canvas","Efficiency",2000,1200);
canvas->Divide(2,2);
TH2D *h2dLimAcc = (TH2D*)Limacc2d->Get("h_Eff")->Clone("2DLimAcc");
h2dLimAcc->GetZaxis()->SetTitle("Acceptance #times Efficiency");
h2dLimAcc->GetXaxis()->SetTitle("Pt [Gev/c]");
h2dLimAcc->GetYaxis()->SetTitle("Multiplicity");
h2dLimAcc->GetXaxis()->CenterTitle();
h2dLimAcc->GetYaxis()->CenterTitle();
h2dLimAcc->GetZaxis()->CenterTitle();
h2dLimAcc->GetXaxis()->SetRangeUser(0.0,24.0);
h2dLimAcc->SetTitle("RecoPID/LimAcc");
canvas->cd(2);
h2dLimAcc->Draw("lego2Z");
TH1D *h1dLimAcc = (TH1D*)Limacc1d->Get("h_Eff")->Clone("1DLimAcc");
h1dLimAcc->SetTitle("RecoPID/LimAcc");
h1dLimAcc->GetXaxis()->SetTitle("Pt [Gev/c]");
h1dLimAcc->GetYaxis()->SetTitle("Acceptance #times Efficiency");
h1dLimAcc->GetXaxis()->SetTitleOffset(1.0);
h1dLimAcc->GetYaxis()->SetTitleOffset(1.0);
h1dLimAcc->GetXaxis()->CenterTitle();
h1dLimAcc->GetYaxis()->CenterTitle();
h1dLimAcc->SetMarkerStyle(21);
h1dLimAcc->SetMarkerSize(0.8);
h1dLimAcc->GetXaxis()->SetRangeUser(0.0,24.0);
canvas->cd(4);
h1dLimAcc->Draw("");
TFile* Genacc2d = TFile::Open("./EfficiencyMap_2D_Dplus5TeV_c_Plot.root");
TH2D *h2dGenAcc = (TH2D*)Genacc2d->Get("c");
h2dGenAcc=(TH2D*)c->FindObject("h_Eff");
h2dGenAcc->GetZaxis()->SetTitle("Efficiency");
h2dGenAcc->GetXaxis()->SetTitle("Pt [Gev/c]");
h2dGenAcc->GetYaxis()->SetTitle("Multiplicity");
h2dGenAcc->GetXaxis()->CenterTitle();
h2dGenAcc->GetYaxis()->CenterTitle();
h2dGenAcc->GetZaxis()->CenterTitle();
h2dGenAcc->GetXaxis()->SetRangeUser(0.0,24.0);
h2dGenAcc->SetTitle("RecoPID/GenAcc");
canvas->cd(1);
h2dGenAcc->Draw("Lego2Z");
TFile* Genacc1d = TFile::Open("./EfficiencyMap_1D_Dplus5TeV_c_Plot.root");
TH1D *h1dGenAcc = (TH1D*)Genacc2d->Get("c");
h1dGenAcc=(TH1D*)c->FindObject("h_Eff");
h1dGenAcc->SetTitle("RecoPID/GenAcc");
h1dGenAcc->GetXaxis()->SetTitle("Pt [Gev/c]");
h1dGenAcc->GetYaxis()->SetTitle("Efficiency");
h1dGenAcc->GetXaxis()->SetTitleOffset(1.0);
h1dGenAcc->GetYaxis()->SetTitleOffset(1.0);
h1dGenAcc->GetXaxis()->CenterTitle();
h1dGenAcc->GetYaxis()->CenterTitle();
h1dGenAcc->SetMarkerStyle(21);
h1dGenAcc->SetMarkerSize(0.8);
h1dGenAcc->GetXaxis()->SetRangeUser(0.0,24.0);
canvas->cd(3);
h1dGenAcc->Draw("");
canvas->SaveAs("./DPlusFinaleff.root");
canvas->SaveAs("./DPlusFinaleff.gif");
}
